
import { precacheAndRoute } from 'workbox-precaching'
import { clientsClaim }from 'workbox-core'

declare const self: ServiceWorkerGlobalScope

// Precache all the assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST)

// Skip waiting and claim clients to take control of the page as soon as possible.
self.skipWaiting()
clientsClaim()

// Listen for the 'push' event, which fires when a push message is received.
self.addEventListener('push', (event: PushEvent) => {
  console.log('Service Worker: Push Received.')

  // Default options for the notification.
  const defaultOptions = {
    body: 'You have a new notification.',
    icon: '/logos/amiko-logo-192.png', // Default icon
    badge: '/logos/amiko-logo-72.png', // Badge for Android
  }

  let notificationData: any = {}
  if (event.data) {
    try {
      notificationData = event.data.json()
    } catch (e) {
      console.log('Service Worker: Push event data is not JSON. Treating as text.')
      notificationData = {
        title: 'New Notification',
        body: event.data.text(),
      }
    }
  }

  const options = {
    ...defaultOptions,
    ...notificationData,
    data: {
      url: notificationData.url || '/', // Default URL to open on click
    },
  }

  const title = notificationData.title || 'Amiko'

  // Show the notification.
  event.waitUntil(
    self.registration.showNotification(title, options)
  )
})

// Listen for the 'notificationclick' event, which fires when a user clicks on a notification.
self.addEventListener('notificationclick', (event) => {
  console.log('Service Worker: Notification clicked.')

  // Close the notification.
  event.notification.close()

  // Open the URL specified in the notification's data.
  event.waitUntil(
    self.clients.openWindow(event.notification.data.url || '/')
  )
})
